version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  bot:
    build: .
    env_file:
      - ./.env
    command: python Telegram.py
    volumes:
      - ./app
    restart: always
    depends_on:
      - redis

  celery:
    build: .
    container_name: celery-worker
    command: celery -A schedule worker -l info
    volumes:
      - ./celery_logs:/celery_logs/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0/
    depends_on:
      - bot
      - redis

volumes:
  celery_logs:
